// Code generated by gen.go; DO NOT EDIT.

// Copyright 2024 Louis Royer and the NextMN-SRv6 contributors. All rights reserved.
// Use of this source code is governed by a MIT-style license that can be
// found in the LICENSE file.

package database

var procedures = map[string]int{
	"insert_uplink_rule": 6,
	"insert_downlink_rule": 5,
	"insert_action": 4,
	"enable_rule": 1,
	"disable_rule": 1,
	"delete_rule": 1,
}
